[window]
  # Blank space added around the window in pixels
  padding = { x = 0, y = 0 } 
  dynamic_padding = true

  # Spread additional padding evenly around the terminal content

  # Disable border and title bar
  # decorations: none

[font]
  normal = { family = "FiraCode Nerd Font", style = "Regular" }
  bold = { family = "FiraCode Nerd Font", style = "Bold" }
  italic = { family = "FiraCode Nerd Font", style = "Bold" }
  size = 16

[env]
  TERM = "xterm-256color"
